# This file was generated by GoReleaser. DO NOT EDIT.
cask "oidc-token-cli" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "70681cb3948d365e25372dae0127399daad7e1211454dea6cea9f864c155459b"
      url "https://github.com/abinnovision/oidc-token-cli/releases/download/v#{version}/oidc-token-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fa17be4099c64a55c44b0f09884a9e2706d1146f1db192b3fa07e871be87d74a"
      url "https://github.com/abinnovision/oidc-token-cli/releases/download/v#{version}/oidc-token-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "68e6b059769bc01e49c792cc02c16fac0e447226c6fdc49143f65abf3bf9b592"
      url "https://github.com/abinnovision/oidc-token-cli/releases/download/v#{version}/oidc-token-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c9c79f1e9001e388b4a03c6254306df1c5c4fbe1dec4bfd0aed3c437a5bd8a8c"
      url "https://github.com/abinnovision/oidc-token-cli/releases/download/v#{version}/oidc-token-cli_linux_arm64.tar.gz"
    end
  end

  name "oidc-token-cli"
  desc "Generic, dynamic OIDC token helper for exec-style credential providers (frpc, kubectl, curl, CI)."
  homepage "https://github.com/abinnovision/oidc-token-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oidc-token"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oidc-token"]
    end
  end

  # No zap stanza required

end
