# This file was generated by GoReleaser. DO NOT EDIT.
cask "oidc-token-cli" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "d35783ee864aca7fdbe1bbb323f80496f3f78846349071401823bda291ad45d5"
      url "https://github.com/abinnovision/oidc-token-cli/releases/download/v#{version}/oidc-token-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "177d7b3e2004d82649b665d5ab03d7d7e68bd4ea4a1f64a7788402d035c90ff8"
      url "https://github.com/abinnovision/oidc-token-cli/releases/download/v#{version}/oidc-token-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "91fee50df92ea0e7389b8b9248ca56f67988d83a645d23c26daac0c554c4754e"
      url "https://github.com/abinnovision/oidc-token-cli/releases/download/v#{version}/oidc-token-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6734f960e70208b394b05870ef52b421b6c107b54af23e4ddc127f8fe4717a0a"
      url "https://github.com/abinnovision/oidc-token-cli/releases/download/v#{version}/oidc-token-cli_linux_arm64.tar.gz"
    end
  end

  name "oidc-token-cli"
  desc "Generic, dynamic OIDC token helper for exec-style credential providers (frpc, kubectl, curl, CI)."
  homepage "https://github.com/abinnovision/oidc-token-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oidc-token"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oidc-token"]
    end
  end

  # No zap stanza required

end
