# This file was generated by GoReleaser. DO NOT EDIT.
cask "oidc-token-cli" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "0c4b13ecea7b0ddb6679b698481a931afa110c6656495092bee3ad4a8bf52491"
      url "https://github.com/abinnovision/oidc-token-cli/releases/download/v#{version}/oidc-token-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5b1d95918b2f846cd87ee4c6540fd34cc6c0eae40fcb77dd50c1bf9b10499b8a"
      url "https://github.com/abinnovision/oidc-token-cli/releases/download/v#{version}/oidc-token-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3c5f534863ed4fdb974caf1e8e796189e3ac10f5089db35f1baed0194590f79c"
      url "https://github.com/abinnovision/oidc-token-cli/releases/download/v#{version}/oidc-token-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5bb8f48caa6b0abc17761cb52c6713a57ea90ddf2360485e08668d14e3d2beb0"
      url "https://github.com/abinnovision/oidc-token-cli/releases/download/v#{version}/oidc-token-cli_linux_arm64.tar.gz"
    end
  end

  name "oidc-token-cli"
  desc "Generic, dynamic OIDC token helper for exec-style credential providers (frpc, kubectl, curl, CI)."
  homepage "https://github.com/abinnovision/oidc-token-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oidc-token"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oidc-token"]
    end
  end

  # No zap stanza required

end
