# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssh-pve" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "0b3b21b7a6c39caa0b6f8278df7a0d4220963aea888b210fc395256568838cba"
      url "https://github.com/abinnovision/ssh-pve/releases/download/v#{version}/ssh-pve_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "582b308422d08a8ed9c6bc580ef0b60ce02e15e76c65f076130c1adda8a3d962"
      url "https://github.com/abinnovision/ssh-pve/releases/download/v#{version}/ssh-pve_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "42eae473c794976a84c75c0324333f884bdc436b958697493d50b2e8fbb5ab88"
      url "https://github.com/abinnovision/ssh-pve/releases/download/v#{version}/ssh-pve_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "98dd254f1c8809d832ea19e3ab0a50f403eeead4db1346a1e0e10b5d95a68522"
      url "https://github.com/abinnovision/ssh-pve/releases/download/v#{version}/ssh-pve_linux_arm64.tar.gz"
    end
  end

  name "ssh-pve"
  desc "A terminal UI for listing Proxmox VE VMs across a whole cluster and shelling into them with a single keypress."
  homepage "https://github.com/abinnovision/ssh-pve"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh-pve"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ssh-pve"]
    end
  end

  # No zap stanza required

end
