# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssh-pve" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "f08f138bf96789655383a2181303a9ba2c7c197782e3d5c1a3ca366084fbd3a1"
      url "https://github.com/abinnovision/ssh-pve/releases/download/v#{version}/ssh-pve_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "66fd0cb7b6f0b0e4c0299958f3484d8b9c4d348df5ac91216b613e6a2fa7f413"
      url "https://github.com/abinnovision/ssh-pve/releases/download/v#{version}/ssh-pve_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "da250cfd9f9ef9e0a232abf63f846606cd1292e228df793b9abf30e260b723ad"
      url "https://github.com/abinnovision/ssh-pve/releases/download/v#{version}/ssh-pve_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f0a749c86eca78319c10044d444603a4065bc419b78effbbf56013318763cab6"
      url "https://github.com/abinnovision/ssh-pve/releases/download/v#{version}/ssh-pve_linux_arm64.tar.gz"
    end
  end

  name "ssh-pve"
  desc "A terminal UI for listing Proxmox VE VMs across a whole cluster and shelling into them with a single keypress."
  homepage "https://github.com/abinnovision/ssh-pve"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssh-pve"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ssh-pve"]
    end
  end

  # No zap stanza required

end
