# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OidcToken < Formula
  desc "Generic, dynamic OIDC token helper for exec-style credential providers (frpc, kubectl, curl, CI)."
  homepage "https://github.com/abinnovision/oidc-token-cli"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abinnovision/oidc-token-cli/releases/download/v0.5.0/oidc-token-cli_darwin_amd64.tar.gz"
      sha256 "f0d7eb01006ae210be71aeb6c86dc9929deb4d91df3928436e3fdbc8a1861335"

      define_method(:install) do
        bin.install "oidc-token"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abinnovision/oidc-token-cli/releases/download/v0.5.0/oidc-token-cli_darwin_arm64.tar.gz"
      sha256 "3c646af4d322f60b5e7f8c7c03f033c066a2eea0b4a0d1ae51d60aebfbbd5fe9"

      define_method(:install) do
        bin.install "oidc-token"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abinnovision/oidc-token-cli/releases/download/v0.5.0/oidc-token-cli_linux_amd64.tar.gz"
      sha256 "4cca9c357f984873727426553dcaa51613d90ffc23fef316bd4aaff06101c274"
      define_method(:install) do
        bin.install "oidc-token"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abinnovision/oidc-token-cli/releases/download/v0.5.0/oidc-token-cli_linux_arm64.tar.gz"
      sha256 "e1795096fa0614e06baf70736866fcefc9e7296aad511be6c594165b3a751505"
      define_method(:install) do
        bin.install "oidc-token"
      end
    end
  end

  test do
    system "#{bin}/oidc-token", "--help"
  end
end
